# Generated by Django 4.0.4 on 2022-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('architecture', models.CharField(max_length=40)),
                ('timestamp', models.CharField(max_length=40)),
                ('epoch', models.IntegerField()),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=40)),
                ('model_id', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('good', models.IntegerField()),
                ('cost_time', models.FloatField()),
                ('timestamp', models.CharField(max_length=40)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
